2025-01-26 21:31:55.580 WARNING (MainThread) [homeassistant.components.switch] Platform rest not ready yet: No route to resource/endpoint: http://192.168.0.97:3000/arc; Retrying in background in 30 seconds
2025-01-26 21:31:55.730 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 258, in _async_setup_integration
    legacy_platforms = await async_extract_config(hass, config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 393, in async_extract_config
    raise ValueError(
        f"Unable to determine type for {platform.name}: {platform.type}"
    )
ValueError: Unable to determine type for ping: None
2025-01-26 21:43:45.093 WARNING (MainThread) [zeroconf] Error with socket 14 (('127.0.0.1', 5353))): [Errno 22] Invalid argument
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 1266, in sendto
    self._sock.sendto(data, addr)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
